language: node_js
node_js:
  - "8"
script:
  - yarn lint
  - yarn test-ci
  - yarn build
cache: yarn
deploy:
  provider: npm
  email:
    secure: "VGp99TGubMoWsVex0cgQaayh9oo+2n3rgfPIArE3FEGAQ1MY1Lv9NUgupJVD2/8jju9NkgXc3Ve3unnqFoEQ+h/25hL+7j0V5NVoIyRO9s5M6sjqIzB88oQkbXD1ALe1pqoRvJ875ncU2fQXD918TSGNfq/wusvy5Ka03S7ehzZHwpWeBhA53Wv2EffIbexl1mzzAaoMgfi+JiSqouoEVesjfjPeHME/eOD+JDgpYGnE5+0/4DhlvdpFNAYlqFRiEmton32bXKcO3lbXO1jWOYgyvO1DtbQfUExZsuy4YguZlxlQ1wYHOo8VDn9C+h3JWGvF9F7H1u6bYbqkjIqmCmM/VVFPW5lj6e5ucuUBeofHrrC9LKZ//CtQhZdcf3lQQKfrmBfrcqhkorVk2tnYsOYfa6F6o/P9IjmtaG33R29Nm/CoHCzvtp6/3eD2jlViumI2tTQG5HpvVfcPPfBwT17cuziWdH1q0f2b1BWAwWCaxfO124fU0fF9wCqF4bIgFB5tcOFaNow3xlaDAHd1JTgfZ4XCpZsHsQM654ef/mnvX5FQ18fd20Xn/6fMJEOw+kE25fGEpCqCBBKhr4/U/llFTV/uguqGJ7yn4zZEXFMYAsVZC4Rf6dY6ePFENi531FyfeOdyKwv3oyqyCmgv9QkvbCX7h5K6XBnyugiZvZE="
  api_key:
    secure: "ZhgbILm6pcyL1h/K4wy+dj8gW4gaBpRkIRnEtPAyg8uQi7io/bHrFXlhYvnfuD+qpyHYcIUvYMPvPfAzRwpTMpYHh3mQCnI/oh/Htnu1eeIfE129xBlB+FxZfcJnXreIUhnLOFT/vwUtuRewK22L6+4wU6bs18U+MdtbgsS1vIk7q0q71L5xKy82kwAsM5pTyVtsl/SRH5A2xp5lSIyvTQSIMhIL2yjVg3d2gCzUc332xIrMrWOZ454jHm/W9f4fwokKD8QM12XA3Rs+Ux0rEP9IIynu2EZZC/zc41WPK1jlsluWWLEFHpXP2CbtgvM55AHO2D5ArQffkFyVS5S1WV+5Cm+sO3aBIUvul2mU7PN5DrJlr2eYYMK063ROdTVUlpTdeMYaUdMZvdoWE0tJbo33ruKECYjx833nQT1gbn78Dsz+6zOKlzyP3Cr2gBstWoF4lVHweDygR6Sg0/fjjNbCnKJq04IEPNBh1X04Gu+ycC2JueFiKZdeh95QhEM8hxyut2LgXOJYhEBhBrRAUN5mgi0rTa7xros/Y+CbdmhQ318fJuV7iyrEQ46O455e+skRTRXGQgfpff0KP98NIoce6QYCe8KzZ49YD6Ziugy5TWgPGXR0FjcNSJeFI0ykp140C0b79O4LgdtnnRtVGuFOpw0nr1oKpSnZLYTYUuM="
  skip_cleanup: true
  on:
    tags: true
